/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboard {
  'activeUsers' : bigint,
  'users' : Array<UserSummary>,
  'totalUsers' : bigint,
  'totalEarnings' : bigint,
  'pendingActivations' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Notice {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : Time,
}
export interface RechargeOffer {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'operatorName' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'referralCode' : string,
  'referrer' : [] | [Principal],
  'balance' : bigint,
  'spinsLeft' : bigint,
  'lastSpinReset' : Time,
  'isActive' : boolean,
  'videoRewards' : Array<VideoReward>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'balance' : bigint,
  'referralCount' : bigint,
  'isActive' : boolean,
}
export interface VideoReward {
  'lastClaimed' : Time,
  'watched' : boolean,
  'videoId' : bigint,
}
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'principal' : Principal,
  'createdAt' : Time,
  'number' : string,
  'amount' : bigint,
}
export type WithdrawalStatus = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotice' : ActorMethod<[string, string], bigint>,
  'addRechargeOffer' : ActorMethod<[string, string, string], bigint>,
  'adminApproveWithdraw' : ActorMethod<[bigint], undefined>,
  'adminRejectWithdraw' : ActorMethod<[bigint], undefined>,
  'approveActivation' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActivationRequests' : ActorMethod<[], Array<[Principal, string]>>,
  'getAdminDashboard' : ActorMethod<[], AdminDashboard>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllWithdrawRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCountdownTarget' : ActorMethod<[], bigint>,
  'getMyWithdrawRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getPayNumber' : ActorMethod<[], string>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRechargeOffers' : ActorMethod<[], Array<RechargeOffer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'removeNotice' : ActorMethod<[bigint], undefined>,
  'removeRechargeOffer' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setCountdownTarget' : ActorMethod<[bigint], undefined>,
  'spin' : ActorMethod<[], bigint>,
  'submitActivation' : ActorMethod<[string, bigint], boolean>,
  'submitReferralCode' : ActorMethod<[string], boolean>,
  'submitWithdrawRequest' : ActorMethod<[string, bigint], bigint>,
  'watchVideo' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];