/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Nat,
  'referralCount' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const AdminDashboard = IDL.Record({
  'activeUsers' : IDL.Nat,
  'users' : IDL.Vec(UserSummary),
  'totalUsers' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'pendingActivations' : IDL.Nat,
});
export const Time = IDL.Int;
export const VideoReward = IDL.Record({
  'lastClaimed' : Time,
  'watched' : IDL.Bool,
  'videoId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'referrer' : IDL.Opt(IDL.Principal),
  'balance' : IDL.Nat,
  'spinsLeft' : IDL.Nat,
  'lastSpinReset' : Time,
  'isActive' : IDL.Bool,
  'videoRewards' : IDL.Vec(VideoReward),
});
export const WithdrawalStatus = IDL.Text;
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'number' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const RechargeOffer = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'operatorName' : IDL.Text,
  'timestamp' : Time,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addRechargeOffer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'adminApproveWithdraw' : IDL.Func([IDL.Nat], [], []),
  'adminRejectWithdraw' : IDL.Func([IDL.Nat], [], []),
  'approveActivation' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActivationRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getAdminDashboard' : IDL.Func([], [AdminDashboard], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllWithdrawRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCountdownTarget' : IDL.Func([], [IDL.Int], ['query']),
  'getMyWithdrawRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getPayNumber' : IDL.Func([], [IDL.Text], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getRechargeOffers' : IDL.Func([], [IDL.Vec(RechargeOffer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'removeNotice' : IDL.Func([IDL.Nat], [], []),
  'removeRechargeOffer' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setCountdownTarget' : IDL.Func([IDL.Int], [], []),
  'spin' : IDL.Func([], [IDL.Nat], []),
  'submitActivation' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'submitReferralCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitWithdrawRequest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'watchVideo' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Nat,
    'referralCount' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const AdminDashboard = IDL.Record({
    'activeUsers' : IDL.Nat,
    'users' : IDL.Vec(UserSummary),
    'totalUsers' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'pendingActivations' : IDL.Nat,
  });
  const Time = IDL.Int;
  const VideoReward = IDL.Record({
    'lastClaimed' : Time,
    'watched' : IDL.Bool,
    'videoId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'referrer' : IDL.Opt(IDL.Principal),
    'balance' : IDL.Nat,
    'spinsLeft' : IDL.Nat,
    'lastSpinReset' : Time,
    'isActive' : IDL.Bool,
    'videoRewards' : IDL.Vec(VideoReward),
  });
  const WithdrawalStatus = IDL.Text;
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'number' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const RechargeOffer = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'operatorName' : IDL.Text,
    'timestamp' : Time,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addRechargeOffer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminApproveWithdraw' : IDL.Func([IDL.Nat], [], []),
    'adminRejectWithdraw' : IDL.Func([IDL.Nat], [], []),
    'approveActivation' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActivationRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getAdminDashboard' : IDL.Func([], [AdminDashboard], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllWithdrawRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCountdownTarget' : IDL.Func([], [IDL.Int], ['query']),
    'getMyWithdrawRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getPayNumber' : IDL.Func([], [IDL.Text], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getRechargeOffers' : IDL.Func([], [IDL.Vec(RechargeOffer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'removeNotice' : IDL.Func([IDL.Nat], [], []),
    'removeRechargeOffer' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setCountdownTarget' : IDL.Func([IDL.Int], [], []),
    'spin' : IDL.Func([], [IDL.Nat], []),
    'submitActivation' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'submitReferralCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitWithdrawRequest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'watchVideo' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };